---
- name: Beginning Playbook message
  debug:
          msg: Beginning the splunk_forwarder role playbook
  
- name: Log execution of the splunk forwarder role main playbook
  local_action: command logger ansible-track playbook:main.yml target:"{{ inventory_hostname }}" check_mode:"{{ ansible_check_mode }}" roles:{{ role_names }} message_type:Beginning
  changed_when: "False"
  check_mode: no   


- import_tasks: create_splunk_user.yml
  
- name: Log conclusion of the splunk forwarder role main playbook
  local_action: command logger ansible-track playbook:main.yml target:"{{ inventory_hostname }}" check_mode:"{{ ansible_check_mode }}" roles:{{ role_names }} message_type:Ending
  changed_when: "False"
  check_mode: no   
     

...
