---

- name: Beginning Playbook message
  debug:
          msg: "Beginning the splunk_forwarder_uf role Check UF playbook "
  
- name: Log execution of the check_uf.yml playbook
  local_action: command logger ansible-track playbook:check_uf.yml target:"{{ inventory_hostname }}" check_mode:"{{ ansible_check_mode }}" roles:{{ role_names }} message_type:Beginning
  changed_when: "False"
  check_mode: no   
  
- name: Check log file for Connected message
  command: grep "Connected to idx"  /opt/splunkforwarder/var/log/splunk/splunkd.log
  check_mode: no
  changed_when: "False"
  ignore_errors: yes
  register: check_connected

- name: debug
  debug:
    msg: "{{ check_connected }}"
  
- name: Log for Check Connected log message 
  local_action: command logger ansible-track playbook:check_uf.yml target:"{{ inventory_hostname }}" check_mode:"{{ ansible_check_mode }}" roles:{{ role_names }} message_type:Failure  message:"Check Connected log message"
  changed_when: "False"
  check_mode: no   
  when: check_connected.rc > 0
  
          

